In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import set_config
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

from lightgbm import LGBMClassifier


In [ ]:
accounts = pd.read_csv('ravenstack_accounts.csv')
churn_events = pd.read_csv('ravenstack_churn_events.csv')
feature_usage = pd.read_csv('ravenstack_feature_usage.csv')
subscription = pd.read_csv('ravenstack_subscriptions.csv')
support = pd.read_csv('ravenstack_support_tickets.csv')

In [ ]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64 
 8   is_trial         500 non-null    bool  
 9   churn_flag       500 non-null    bool  
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB


In [ ]:
churn_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   churn_event_id            600 non-null    object 
 1   account_id                600 non-null    object 
 2   churn_date                600 non-null    object 
 3   reason_code               600 non-null    object 
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool   
 6   preceding_downgrade_flag  600 non-null    bool   
 7   is_reactivation           600 non-null    bool   
 8   feedback_text             452 non-null    object 
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB


In [ ]:
feature_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64 
 5   usage_duration_secs  25000 non-null  int64 
 6   error_count          25000 non-null  int64 
 7   is_beta_feature      25000 non-null  bool  
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB


In [ ]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64 
 6   mrr_amount         5000 non-null   int64 
 7   arr_amount         5000 non-null   int64 
 8   is_trial           5000 non-null   bool  
 9   upgrade_flag       5000 non-null   bool  
 10  downgrade_flag     5000 non-null   bool  
 11  churn_flag         5000 non-null   bool  
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool  
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB


In [ ]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   ticket_id                    2000 non-null   object 
 1   account_id                   2000 non-null   object 
 2   submitted_at                 2000 non-null   object 
 3   closed_at                    2000 non-null   object 
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object 
 6   first_response_time_minutes  2000 non-null   int64  
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool   
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB


In [ ]:
accounts['industry'].unique()

array(['EdTech', 'FinTech', 'DevTools', 'HealthTech', 'Cybersecurity'],
      dtype=object)

In [ ]:
accounts['country'].unique()

array(['US', 'IN', 'UK', 'CA', 'DE', 'AU', 'FR'], dtype=object)

In [ ]:
accounts['referral_source'].unique()

array(['partner', 'other', 'organic', 'event', 'ads'], dtype=object)

In [ ]:
accounts['plan_tier'].unique()

array(['Basic', 'Enterprise', 'Pro'], dtype=object)

In [ ]:
churn_events.sample(2)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
82,C-480232,A-31ab9a,2024-09-23,competitor,0.0,False,False,True,too expensive
260,C-8c9a9a,A-9f0b68,2024-08-10,features,0.0,True,False,False,too expensive


In [ ]:
churn_events['churn_date'] = pd.to_datetime(churn_events['churn_date'])

In [ ]:
churn_events_cpy = pd.get_dummies(churn_events, columns=['reason_code', 'feedback_text'], dtype=int)
churn_events_cpy.drop(columns=['churn_event_id'], inplace=True)
churn_events_cpy.sample(2)

,account_id,churn_date,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing features,feedback_text_switched to competitor,feedback_text_too expensive
19,A-1e50e0,2024-04-26,0.0,False,False,False,0,0,0,1,0,0,0,1,0
139,A-ed510f,2023-05-05,0.0,False,False,False,1,0,0,0,0,0,0,0,1


In [ ]:
churn_events_cpy.rename(columns={
    'feedback_text_missing features': 'feedback_text_missing_features',
    'feedback_text_switched to competitor': 'feedback_text_switched_to_competitor',
    'feedback_text_too expensive': 'feedback_text_too_expensive'
}, inplace=True)

In [ ]:
churn_events_cpy.columns

Index(['account_id', 'churn_date', 'refund_amount_usd',
       'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation',
       'reason_code_budget', 'reason_code_competitor', 'reason_code_features',
       'reason_code_pricing', 'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive'],
      dtype='object')

In [ ]:
churn_events_cpy

,account_id,churn_date,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing_features,feedback_text_switched_to_competitor,feedback_text_too_expensive
0,A-c37cab,2024-10-27,4.03,False,False,False,0,0,0,1,0,0,0,1,0
1,A-37f969,2024-06-25,96.45,True,False,False,0,0,0,0,1,0,0,0,0
2,A-b07346,2024-11-12,0.00,False,False,False,1,0,0,0,0,0,1,0,0
3,A-1e50e0,2023-11-01,54.94,False,False,False,1,0,0,0,0,0,0,1,0
4,A-956988,2024-12-30,0.00,False,True,True,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,A-702032,2024-06-14,0.00,False,False,False,0,1,0,0,0,0,0,1,0
596,A-dbc825,2024-02-03,0.00,False,False,False,1,0,0,0,0,0,0,0,0
597,A-0a282f,2024-12-31,62.66,False,True,False,0,0,0,0,1,0,0,0,1
598,A-e5d6ab,2024-05-11,0.00,True,False,False,0,1,0,0,0,0,0,0,0


In [ ]:
churn_events_cpy = churn_events_cpy.groupby('account_id').agg({
    'churn_date': 'max',
    'refund_amount_usd': 'sum',
    'preceding_upgrade_flag': 'sum',
    'preceding_downgrade_flag': 'sum',
    'is_reactivation' : 'sum',
    'reason_code_budget': 'sum',
    'reason_code_competitor': 'sum',
    'reason_code_features': 'sum',
    'reason_code_pricing': 'sum',
    'reason_code_support': 'sum',
    'reason_code_unknown': 'sum',
    'feedback_text_missing_features': 'sum',
    'feedback_text_switched_to_competitor': 'sum',
    'feedback_text_too_expensive': 'sum'}).reset_index()

In [ ]:
final_df = accounts.merge(churn_events_cpy, on='account_id', how='left')

In [ ]:
final_df['account_id'].nunique()

500

In [ ]:
final_df

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,...,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing_features,feedback_text_switched_to_competitor,feedback_text_too_expensive
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0


In [ ]:
feature_usage.sample(2)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
16091,U-160f00,S-61e53d,2024-10-01,feature_15,12,2484,1,False
3450,U-183059,S-a2afb0,2023-04-30,feature_14,9,1899,0,False


In [ ]:
subscription.sample(2)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
4943,S-9c9700,A-0f6450,2024-12-31,NaN,Basic,28,532,6384,False,False,False,False,annual,True
2377,S-9e74ba,A-b48f73,2024-12-06,NaN,Enterprise,80,0,0,True,False,False,False,annual,True


In [ ]:
subscription['subscription_id'].nunique()

5000

In [ ]:
feature_usage['subscription_id'].nunique()

4967

In [ ]:
feature_usage['usage_date'] = pd.to_datetime(feature_usage['usage_date'])

In [ ]:
feature_usage_cpy = pd.get_dummies(feature_usage, columns=['feature_name'], dtype=int)
feature_usage_cpy.drop(columns=['usage_id'], inplace=True)
feature_usage_cpy.sample(2)

,subscription_id,usage_date,usage_count,usage_duration_secs,error_count,is_beta_feature,feature_name_feature_1,feature_name_feature_10,feature_name_feature_11,feature_name_feature_12,...,feature_name_feature_37,feature_name_feature_38,feature_name_feature_39,feature_name_feature_4,feature_name_feature_40,feature_name_feature_5,feature_name_feature_6,feature_name_feature_7,feature_name_feature_8,feature_name_feature_9
23594,S-f50afe,2024-02-14,10,340,0,False,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9196,S-fd648e,2024-11-17,4,1148,0,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
cols_to_sum = feature_usage_cpy.columns.difference(['subscription_id', 'usage_date'])
feature_usage_cpy = feature_usage_cpy.groupby('subscription_id').agg({
    'usage_date': 'max',
    **{col: 'sum' for col in cols_to_sum}
}).reset_index()

In [ ]:
subscription = subscription.merge(feature_usage_cpy, on='subscription_id', how='left')

In [ ]:
subscription['billing_frequency']

,billing_frequency
0,monthly
1,monthly
2,annual
3,monthly
4,monthly
...,...
4995,monthly
4996,monthly
4997,annual
4998,monthly


In [ ]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   subscription_id          5000 non-null   object        
 1   account_id               5000 non-null   object        
 2   start_date               5000 non-null   object        
 3   end_date                 486 non-null    object        
 4   plan_tier                5000 non-null   object        
 5   seats                    5000 non-null   int64         
 6   mrr_amount               5000 non-null   int64         
 7   arr_amount               5000 non-null   int64         
 8   is_trial                 5000 non-null   bool          
 9   upgrade_flag             5000 non-null   bool          
 10  downgrade_flag           5000 non-null   bool          
 11  churn_flag               5000 non-null   bool          
 12  billing_frequency        5000 non-

In [ ]:
subscription['start_date'] = pd.to_datetime(subscription['start_date'])
subscription['end_date'] = pd.to_datetime(subscription['end_date'])

In [ ]:
subscription_cpy = pd.get_dummies(subscription, columns=['plan_tier', 'billing_frequency'], dtype=int)
subscription_cpy.drop(columns=['subscription_id'], inplace=True)
subscription_cpy.sample(2)

,account_id,start_date,end_date,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,...,feature_name_feature_8,feature_name_feature_9,is_beta_feature,usage_count,usage_duration_secs,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,billing_frequency_annual,billing_frequency_monthly
3122,A-098560,2023-12-10,NaT,35,1715,20580,False,True,False,False,...,0.0,0.0,1.0,53.0,14349.0,0,0,1,1,0
475,A-726cfa,2023-08-10,NaT,30,5970,71640,False,False,False,False,...,0.0,0.0,1.0,30.0,8236.0,0,1,0,1,0


In [ ]:
subscription_cpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 61 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   account_id                 5000 non-null   object        
 1   start_date                 5000 non-null   datetime64[ns]
 2   end_date                   486 non-null    datetime64[ns]
 3   seats                      5000 non-null   int64         
 4   mrr_amount                 5000 non-null   int64         
 5   arr_amount                 5000 non-null   int64         
 6   is_trial                   5000 non-null   bool          
 7   upgrade_flag               5000 non-null   bool          
 8   downgrade_flag             5000 non-null   bool          
 9   churn_flag                 5000 non-null   bool          
 10  auto_renew_flag            5000 non-null   bool          
 11  usage_date                 4967 non-null   datetime64[ns]
 12  error_

In [ ]:
col_to_sum = subscription_cpy.columns.difference(['account_id', 'start_date', 'end_date', 'usage_date'])
subscription_cpy = subscription_cpy.groupby('account_id').agg({
    'start_date': 'min',
    'end_date': 'max',
    'usage_date': 'max',
    **{col: 'sum' for col in col_to_sum}
}).reset_index()



In [ ]:
final_df = final_df.merge(subscription_cpy, on='account_id', how='left')

In [ ]:
final_df

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats_x,is_trial_x,churn_flag_x,...,is_beta_feature,is_trial_y,mrr_amount,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,seats_y,upgrade_flag,usage_count,usage_duration_secs
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,4.0,2,12603,3,2,5,312,1,535.0,152339.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,...,2.0,0,10004,4,1,3,176,3,355.0,101136.0
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,...,5.0,1,18286,4,4,7,282,1,821.0,251210.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,...,5.0,1,9275,3,1,3,209,2,382.0,102528.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,...,4.0,1,48761,0,4,5,424,2,579.0,215779.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False,...,5.0,1,4447,4,1,3,221,0,402.0,130242.0
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False,...,6.0,3,12137,2,3,5,188,3,476.0,145972.0
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True,...,3.0,4,16613,2,4,3,202,0,458.0,121379.0
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False,...,4.0,2,19382,4,4,4,341,1,571.0,180056.0


In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 84 columns):
 #   Column                                Non-Null Count  Dtype         
---  ------                                --------------  -----         
 0   account_id                            500 non-null    object        
 1   account_name                          500 non-null    object        
 2   industry                              500 non-null    object        
 3   country                               500 non-null    object        
 4   signup_date                           500 non-null    object        
 5   referral_source                       500 non-null    object        
 6   plan_tier                             500 non-null    object        
 7   seats_x                               500 non-null    int64         
 8   is_trial_x                            500 non-null    bool          
 9   churn_flag_x                          500 non-null    bool          
 10  ch

In [ ]:
support.sample(2)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
1126,T-334013,A-3be56b,2023-07-17,2023-07-19 17:00:00,65.0,medium,96,4.0,False
396,T-60c481,A-5247b3,2024-07-29,2024-07-31 09:00:00,57.0,urgent,131,4.0,False


In [ ]:
support['account_id'].nunique()

492

In [ ]:
support['submitted_at'] = pd.to_datetime(support['submitted_at'])
support['closed_at'] = pd.to_datetime(support['closed_at'])


In [ ]:
support_cpy = pd.get_dummies(support, columns=['priority'], dtype=int)
support_cpy.drop(columns=['ticket_id'], inplace=True)
support_cpy.sample(2)

,account_id,submitted_at,closed_at,resolution_time_hours,first_response_time_minutes,satisfaction_score,escalation_flag,priority_high,priority_low,priority_medium,priority_urgent
520,A-19b2c8,2023-02-03,2023-02-04 08:00:00,32.0,132,4.0,False,0,0,1,0
775,A-dcc3f1,2024-03-20,2024-03-21 16:00:00,40.0,3,3.0,False,0,0,0,1


In [ ]:
support_cpy = support_cpy.groupby('account_id').agg({
    'submitted_at': ['min', 'max'],
    'closed_at': ['min', 'max'],
    'resolution_time_hours': 'mean',
    'first_response_time_minutes': 'mean',
    'satisfaction_score': 'mean',
    'escalation_flag': 'sum',
    'priority_urgent': 'sum',
    'priority_high': 'sum',
    'priority_low': 'sum',
    'priority_medium': 'sum'})

In [ ]:
support_cpy.columns = [
    '_'.join(col).strip() if isinstance(col, tuple) else col
    for col in support_cpy.columns
]

In [ ]:
final_df = final_df.merge(support_cpy, on='account_id', how='left')

In [ ]:
final_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats_x', 'is_trial_x', 'churn_flag_x',
       'churn_date', 'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'reason_code_budget',
       'reason_code_competitor', 'reason_code_features', 'reason_code_pricing',
       'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive',
       'start_date', 'end_date', 'usage_date', 'arr_amount', 'auto_renew_flag',
       'billing_frequency_annual', 'billing_frequency_monthly', 'churn_flag_y',
       'downgrade_flag', 'error_count', 'feature_name_feature_1',
       'feature_name_feature_10', 'feature_name_feature_11',
       'feature_name_feature_12', 'feature_name_feature_13',
       'feature_name_feature_14', 'feature_name_feature_15',
       'feature_name_feature_16', 'featu

In [ ]:
# final_df.to_csv('final_SaaS_Churning_dataset')

In [ ]:
final_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats_x', 'is_trial_x', 'churn_flag_x',
       'churn_date', 'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'reason_code_budget',
       'reason_code_competitor', 'reason_code_features', 'reason_code_pricing',
       'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive',
       'start_date', 'end_date', 'usage_date', 'arr_amount', 'auto_renew_flag',
       'billing_frequency_annual', 'billing_frequency_monthly', 'churn_flag_y',
       'downgrade_flag', 'error_count', 'feature_name_feature_1',
       'feature_name_feature_10', 'feature_name_feature_11',
       'feature_name_feature_12', 'feature_name_feature_13',
       'feature_name_feature_14', 'feature_name_feature_15',
       'feature_name_feature_16', 'featu

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 96 columns):
 #   Column                                Non-Null Count  Dtype         
---  ------                                --------------  -----         
 0   account_id                            500 non-null    object        
 1   account_name                          500 non-null    object        
 2   industry                              500 non-null    object        
 3   country                               500 non-null    object        
 4   signup_date                           500 non-null    object        
 5   referral_source                       500 non-null    object        
 6   plan_tier                             500 non-null    object        
 7   seats_x                               500 non-null    int64         
 8   is_trial_x                            500 non-null    bool          
 9   churn_flag_x                          500 non-null    bool          
 10  ch

In [ ]:
(final_df['churn_flag_x'] == final_df['churn_flag_y']).all()

np.False_

In [ ]:
(final_df['seats_x'] == final_df['seats_y']).all()

np.False_

In [ ]:
(final_df['is_trial_x'] == final_df['is_trial_y']).all()

np.False_

In [ ]:
final_df.rename(columns={
    'churn_flag_x': 'churn_flag',
    'churn_flag_y': 'past_churn_count',
    'is_trial_x': 'is_trial_current',
    'is_trial_y': 'trial_count'
}, inplace=True)

In [ ]:
final_df.drop(columns=['seats_y'], inplace=True)

In [ ]:
final_df['signup_date'] = pd.to_datetime(final_df['signup_date'])

In [ ]:
def drop_columns(df, features):
    df.drop(columns=features, inplace=True)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 95 columns):
 #   Column                                Non-Null Count  Dtype         
---  ------                                --------------  -----         
 0   account_id                            500 non-null    object        
 1   account_name                          500 non-null    object        
 2   industry                              500 non-null    object        
 3   country                               500 non-null    object        
 4   signup_date                           500 non-null    datetime64[ns]
 5   referral_source                       500 non-null    object        
 6   plan_tier                             500 non-null    object        
 7   seats_x                               500 non-null    int64         
 8   is_trial_current                      500 non-null    bool          
 9   churn_flag                            500 non-null    bool          
 10  ch

In [ ]:
# ('usage_per_day', 'usage_count', 'account_age_days')
# ('account_age_days', 'usage_date', 'signup_date')
# final_df['account_age_days'] = (final_df['usage_date'] - final_df['signup_date']).dt.days
# final_df['account_age_days'].days
# final_df['usage_per_day'] = final_df['usage_count'] / (final_df['account_age_days'])
# final_df['usage_per_day']

#  final_df['support_pressure'] = (final_df['priority_urgent_sum'] * 4) + (final_df['priority_high_sum'] * 3) +(final_df['priority_medium_sum'] * 2) + final_df['priority_low_sum']
# final_df['support_pressure'] = (
#     (final_df['priority_urgent_sum'] * 4) +
#     (final_df['priority_high_sum'] * 3) +
#     (final_df['priority_medium_sum'] * 2) +
#     final_df['priority_low_sum']
# )
# final_df['support_pressure']


In [ ]:
# class FeatureConstructor(BaseEstimator, TransformerMixin):

#   def n_construction_days(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = (df[feature2]-df[feature3]).dt.days
#     return df

#   def n_construction(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = (df[feature2]-df[feature3])
#     return df

#   def d_construction(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = df[feature2]/df[feature3]
#     return df

#   def add_support_flag(self, df):
#     df = df.copy()
#     df['support_flag'] = (df['resolution_time_hours_mean'] > 0).astype(int)
#     return df

#   def add_support_pressure(self, df):
#     df = df.copy()
#     df['support_pressure'] = (
#         df['priority_urgent_sum'] * 4 +
#         df['priority_high_sum'] * 3 +
#         df['priority_medium_sum'] * 2 +
#         df['priority_low_sum']
#     )
#     return df

#   def add_support_risk(self, df):
#     df = df.copy()
#     df['support_risk'] = 5 - df['satisfaction_score_mean']
#     return df

#   def add_feature_usage_metrics(self, df):
#     df = df.copy()
#     feature_cols = [col for col in df.columns if "feature_name_" in col]
#     df['feature_adoption_score'] = df[feature_cols].sum(axis=1)
#     df['features_used_count'] = (df[feature_cols] > 0).sum(axis=1)
#     return df

#   def add_days_since_last_usage(self, df, date_col='usage_date'):
#     df = df.copy()
#     observation_date = df[date_col].max()
#     df['days_since_last_usage'] = (observation_date - df[date_col]).dt.days
#     return df








In [ ]:
class FeatureConstructor(BaseEstimator, TransformerMixin):

    def __init__(self, day_features=None, diff_features=None, ratio_features=None):
        self.day_features = day_features
        self.diff_features = diff_features
        self.ratio_features = ratio_features



    def fit(self, X, y=None):
        # X['account_age_days'] = (X["usage_date"] - X["signup_date"]).dt.days


        # self.threshold1 = X["usage_per_day"].quantile(0.3)
        # self.threshold2 = X["support_pressure"].quantile(0.7)
        return self

    def transform(self, X):
        df = X.copy()
        if self.day_features:
            for new_col, col1, col2 in self.day_features:
                df[new_col] = (df[col1] - df[col2]).dt.days

        if self.diff_features:
            for new_col, col1, col2 in self.diff_features:
                df[new_col] = df[col1] - df[col2]

        if self.ratio_features:
            for new_col, col1, col2 in self.ratio_features:
                df[new_col] = df[col1] / df[col2]

        df['subscription_duration_days'] = (df['end_date'] - df['start_date']).dt.days
        df.loc[df['start_date'].isna() & df['end_date'].isna(),'subscription_duration_days'] = 0
        today = df['usage_date'].max()
        df.loc[df['end_date'].isna() & df['start_date'].notna(),'subscription_duration_days'] = (today - df['start_date']).dt.days

        df['ticket_span_days'] = (df['closed_at_max'] - df['submitted_at_min']).dt.days
        df.loc[df['submitted_at_min'].isna() & df['closed_at_max'].isna(),'ticket_span_days'] = 0
        # today1 = df['usage_date'].max()
        df.loc[df['closed_at_max'].isna() & df['submitted_at_min'].notna(),'ticket_span_days'] = (today - df['submitted_at_min']).dt.days














        df["expected_usage"] = df["seats_x"] * 10
        df["usage_gap"] = df["usage_count"] - df["expected_usage"]

        df['support_flag'] = (df['resolution_time_hours_mean'] > 0).astype(int)
        df["usage_per_day"] = df["usage_count"] / (df["account_age_days"] + 1)

        df['support_pressure'] = (
            df['priority_urgent_sum'] * 4 +
            df['priority_high_sum'] * 3 +
            df['priority_medium_sum'] * 2 +
            df['priority_low_sum']
        )

        df["support_per_usage"] = df["support_pressure"] / (df["usage_count"] + 1)

        df['support_risk'] = 5 - df['satisfaction_score_mean']

        feature_cols = [c for c in df.columns if "feature_name_" in c]
        df['feature_adoption_score'] = df[feature_cols].sum(axis=1)

        df['features_used_count'] = (df[feature_cols] > 0).sum(axis=1)
        df["stickiness"] = df["features_used_count"] / (df["account_age_days"] + 1)

        df["account_age_ratio"] = df["account_age_days"] / (df["subscription_duration_days"] + 1)
        df["usage_per_seat"] = df["usage_count"] / (df["seats_x"] + 1)
        observation_date = df['usage_date'].max()
        df['days_since_last_usage'] = (observation_date - df['usage_date']).dt.days





        df["frustration_score"] = (df["support_pressure"] * 0.5 +(5 - df["satisfaction_score_mean"].fillna(3)) * 2)
        df["revenue_per_seat"] = df["arr_amount"] / (df["seats_x"] + 1)
        return df


In [ ]:

def select_features(df):
    feature_cols = [col for col in df.columns if "feature_name_" in col]
    leakage_cols = [
    'churn_date',
    'refund_amount_usd',

    'is_reactivation',
    'reason_code_budget',
    'reason_code_competitor',
    'reason_code_features',
    'reason_code_pricing',
    'reason_code_support',
    'reason_code_unknown',
    'feedback_text_missing_features',
    'feedback_text_switched_to_competitor',
    'feedback_text_too_expensive'
    ]
    IDs = ['account_id', 'account_name']
    raw_dates = [
    'signup_date',
    'start_date',
    'end_date',
    'usage_date',
    'submitted_at_min',
    'submitted_at_max',
    'closed_at_min',
    'closed_at_max'
    ]
    features_to_remove = leakage_cols + IDs + raw_dates + feature_cols
    return df.drop(columns=[c for c in features_to_remove if c in df.columns])

select_features_transformer = FunctionTransformer(select_features)

In [ ]:
def drop_columns(df):
    return df.drop(columns=['industry','country','referral_source','plan_tier'], errors="ignore")

drop_columns_transformer = FunctionTransformer(drop_columns)

In [ ]:
def fill_subscription_duration(df):
    df = df.copy()
    df["subscription_duration_days"] = df["subscription_duration_days"].fillna(df["account_age_days"])
    return df

fill_duration_transformer = FunctionTransformer(fill_subscription_duration)


In [ ]:
X = final_df.drop(columns=['churn_flag'])
y = final_df['churn_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
set_config(transform_output="pandas")
imputation = ColumnTransformer(
    transformers=[
        ('constant_imputation', SimpleImputer(strategy='constant', fill_value=0), [
            'resolution_time_hours_mean',
            'first_response_time_minutes_mean',
            'escalation_flag_sum',
            'priority_urgent_sum',
            'priority_high_sum',
            'priority_low_sum',
            'priority_medium_sum',



            'preceding_upgrade_flag',
            'preceding_downgrade_flag']),
        ('median_imputation', SimpleImputer(strategy='median'), ['satisfaction_score_mean'])
    ],
    remainder='passthrough',
    verbose_feature_names_out=False)

feature_construction = FeatureConstructor(
    day_features=[
        ('account_age_days', 'usage_date', 'signup_date')
    ],

    diff_features=[
        ('plan_momentum', 'preceding_upgrade_flag', 'preceding_downgrade_flag')
    ],

    ratio_features=[
        ('avg_usage_time', 'usage_duration_secs', 'usage_count'),
        ('reveneu_per_seat', 'arr_amount', 'seats_x')
    ]

)

select_features_transformer = FunctionTransformer(select_features, validate=False)

feature_transformation = ColumnTransformer(
    transformers=[
        ('onehotencoding', OneHotEncoder(sparse_output=False, drop='first'), ['industry', 'country', 'referral_source']),
        ('ordinalencoding', OrdinalEncoder(), ['plan_tier'])],
    remainder='passthrough', verbose_feature_names_out=False)

feature_drop = FunctionTransformer(drop_columns, validate=False)

model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    class_weight='balanced',
    random_state=42
)





In [ ]:
# pipe = Pipeline([
#     ('imputation', imputation),
#     ('feature_construction', feature_construction),
#     ('feature_selection', select_features_transformer),
#     ('feature_transformation', feature_transformation),
#     ('feature_drop', feature_drop),
#     ('model', model)
#     ])

In [ ]:
from imblearn.pipeline import Pipeline as ImbPipeline

xgb_pipe = ImbPipeline([
    ('imputation', imputation),
    ('feature_construction', feature_construction),
    ('feature_selection', select_features_transformer),
    ('feature_transformation', feature_transformation),
    ('feature_drop', feature_drop),

    # SMOTE must come AFTER full preprocessing
    ('smote', SMOTE(random_state=42, k_neighbors=3)),

    ('model', LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        num_leaves=31,
        class_weight='balanced',
        random_state=42
    ))
])

In [ ]:
xgb_pipe.fit(X_train, y_train)


[LightGBM] [Info] Number of positive: 307, number of negative: 307
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000593 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5518
[LightGBM] [Info] Number of data points in the train set: 614, number of used features: 63
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive 

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('imputation',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('constant_imputation',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant'),
                                                  ['resolution_time_hours_mean',
                                                   'first_response_time_minutes_mean',
                                                   'escalation_flag_sum',
                                                   'priority_urgent_sum',
                                                   'priority_high_sum',
                                                   'priority_low_sum',
                                                   'priority_medium_sum',
                                                   'preceding_upgrade_flag...
                                                  ['industry', 'country',
                                                   'referral_source']),
                                                 ('ordinalencoding',
                                                  OrdinalEncoder(),
                                                  ['plan_tier'])],
                                   verbose_feature_names_out=False)),
                ('feature_drop',
                 FunctionTransformer(func=<function drop_columns at 0x7bbe1af036a0>)),
                ('smote', SMOTE(k_neighbors=3, random_state=42)),
                ('model',
                 LGBMClassifier(class_weight='balanced', learning_rate=0.05,
                                n_estimators=300, random_state=42))])

In [ ]:
# param_dist = {
#     'model__n_estimators': [100, 200, 300, 500],
#     'model__max_depth': [3, 5, 7, 10, None],
#     'model__min_samples_split': [2, 5, 10, 20],
#     'model__min_samples_leaf': [1, 2, 5, 10],
#     'model__max_features': ['sqrt', 'log2', None]
# }

In [ ]:
# param_dist = {
#     'model__n_estimators': [100, 200, 300, 500],
#     'model__max_depth': [3, 5, 6, 8],
#     'model__learning_rate': [0.01, 0.05, 0.1, 0.2],
#     'model__subsample': [0.6, 0.8, 1.0],
#     'model__colsample_bytree': [0.6, 0.8, 1.0],
#     'model__gamma': [0, 0.1, 0.3],
# }

In [ ]:
# random_search = RandomizedSearchCV(
#     estimator=pipe,
#     param_distributions=param_dist,
#     n_iter=20,
#     scoring='recall',
#     cv=5,
#     n_jobs=-1,
#     verbose=2,
#     random_state=42
# )

In [ ]:
# random_search.fit(X_train, y_train)

In [ ]:
# random_search.best_params_

In [ ]:
# best_model = random_search.best_estimator_

In [ ]:
# from sklearn.model_selection import RandomizedSearchCV
# from sklearn.ensemble import RandomForestClassifier

# rf_pipe = Pipeline([
#     ('preprocess', pipe),
#     ('model', RandomForestClassifier(class_weight='balanced', random_state=42))
# ])

# rf_param_dist = {
#     'model__n_estimators': [100, 200, 300, 500],
#     'model__max_depth': [3, 5, 7, 10, None],
#     'model__min_samples_split': [2, 5, 10, 20],
#     'model__min_samples_leaf': [1, 2, 5, 10],
#     'model__max_features': ['sqrt', 'log2', None]
# }

# rf_search = RandomizedSearchCV(
#     rf_pipe,
#     rf_param_dist,
#     n_iter=20,
#     scoring='recall',
#     cv=3,
#     n_jobs=-1,
#     verbose=2,
#     random_state=42
# )

# rf_search.fit(X_train, y_train)

In [ ]:
# from xgboost import XGBClassifier

# xgb_pipe = Pipeline([
#     ('preprocess', preprocess_pipe),
#     ('model', XGBClassifier(eval_metric='logloss', random_state=42))
# ])

# xgb_param_dist = {
#     'model__n_estimators': [100, 200, 300, 500],
#     'model__max_depth': [3, 4, 5, 6, 8],
#     'model__learning_rate': [0.01, 0.05, 0.1, 0.2],
#     'model__subsample': [0.6, 0.8, 1.0],
#     'model__colsample_bytree': [0.6, 0.8, 1.0],
#     'model__scale_pos_weight': [1, 2, 5, 10]
# }

# xgb_search = RandomizedSearchCV(
#     xgb_pipe,
#     xgb_param_dist,
#     n_iter=20,
#     scoring='recall',
#     cv=3,
#     n_jobs=-1,
#     verbose=2,
#     random_state=42
# )

# xgb_search.fit(X_train, y_train)

In [ ]:
# best_rf = rf_search.best_estimator_
# best_xgb = xgb_search.best_estimator_

In [ ]:
# rf_proba = best_rf.predict_proba(X_test)[:, 1]
# xgb_proba = best_xgb.predict_proba(X_test)[:, 1]

# ensemble_proba = (rf_proba + xgb_proba) / 2

# y_pred = (ensemble_proba >= 0.3).astype(int)

In [ ]:
# from sklearn.metrics import confusion_matrix, classification_report

# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))

In [ ]:
# for t in [1,0.9,0.8,0.7,0.6,0.5,0.55, 0.4, 0.3, 0.25, 0.2, 0.1, 0.05]:
#     y_pred = (ensemble_proba > t).astype(int)
#     print(f"Threshold: {t}")
#     print(confusion_matrix(y_test, y_pred))

In [ ]:
y_pred = xgb_pipe.predict(X_test)

In [ ]:
import numpy as np
print(np.unique(y_test, return_counts=True))

(array([False,  True]), array([83, 17]))


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[78  5]
 [16  1]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.83      0.94      0.88        83
        True       0.17      0.06      0.09        17

    accuracy                           0.79       100
   macro avg       0.50      0.50      0.48       100
weighted avg       0.72      0.79      0.75       100



In [ ]:
y_proba = xgb_pipe.predict_proba(X_test)[:, 1]

In [ ]:
for t in [1,0.9,0.8,0.7,0.6,0.5,0.55, 0.4, 0.3, 0.25, 0.2, 0.1, 0.05]:
    y_pred = (y_proba > t).astype(int)
    print(f"Threshold: {t}")
    print(confusion_matrix(y_test, y_pred))

Threshold: 1
[[83  0]
 [17  0]]
Threshold: 0.9
[[83  0]
 [17  0]]
Threshold: 0.8
[[82  1]
 [17  0]]
Threshold: 0.7
[[79  4]
 [17  0]]
Threshold: 0.6
[[78  5]
 [16  1]]
Threshold: 0.5
[[78  5]
 [16  1]]
Threshold: 0.55
[[78  5]
 [16  1]]
Threshold: 0.4
[[78  5]
 [16  1]]
Threshold: 0.3
[[73 10]
 [16  1]]
Threshold: 0.25
[[73 10]
 [16  1]]
Threshold: 0.2
[[71 12]
 [14  3]]
Threshold: 0.1
[[58 25]
 [14  3]]
Threshold: 0.05
[[47 36]
 [11  6]]


In [ ]:
from sklearn.calibration import CalibratedClassifierCV

calibrated_model = CalibratedClassifierCV(
    estimator=best_model,
    method='isotonic',   # or 'sigmoid'
    cv=5
)

In [ ]:
calibrated_model.fit(X_train, y_train)

In [ ]:
y_proba = calibrated_model.predict_proba(X_test)[:, 1]
y_pred = (y_proba >= 0.3).astype(int)

In [ ]:
for t in [1,0.9,0.8,0.7,0.6,0.5,0.55, 0.4, 0.3, 0.25, 0.2, 0.1, 0.05]:
    y_pred = (y_proba > t).astype(int)
    print(f"Threshold: {t}")
    print(confusion_matrix(y_test, y_pred))

In [ ]:
threshold = 0.3
y_pred = (y_prob >= threshold).astype(int)

In [ ]:
def predict_with_threshold(model, X, threshold=0.3):
    probs = model.predict_proba(X)[:, 1]
    return (probs >= threshold).astype(int), probs

In [ ]:
y_pred, y_prob = predict_with_threshold(best_model, X_test, 0.3)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))