In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import set_config
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

from lightgbm import LGBMClassifier

In [ ]:
accounts = pd.read_csv('ravenstack_accounts.csv')
# churn_events = pd.read_csv('ravenstack_churn_events.csv')
feature_usage = pd.read_csv('ravenstack_feature_usage.csv')
subscription = pd.read_csv('ravenstack_subscriptions.csv')
support = pd.read_csv('ravenstack_support_tickets.csv')

In [ ]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64 
 8   is_trial         500 non-null    bool  
 9   churn_flag       500 non-null    bool  
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB


In [ ]:
feature_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64 
 5   usage_duration_secs  25000 non-null  int64 
 6   error_count          25000 non-null  int64 
 7   is_beta_feature      25000 non-null  bool  
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB


In [ ]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64 
 6   mrr_amount         5000 non-null   int64 
 7   arr_amount         5000 non-null   int64 
 8   is_trial           5000 non-null   bool  
 9   upgrade_flag       5000 non-null   bool  
 10  downgrade_flag     5000 non-null   bool  
 11  churn_flag         5000 non-null   bool  
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool  
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB


In [ ]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   ticket_id                    2000 non-null   object 
 1   account_id                   2000 non-null   object 
 2   submitted_at                 2000 non-null   object 
 3   closed_at                    2000 non-null   object 
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object 
 6   first_response_time_minutes  2000 non-null   int64  
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool   
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB


In [ ]:
accounts['industry'].unique()

array(['EdTech', 'FinTech', 'DevTools', 'HealthTech', 'Cybersecurity'],
      dtype=object)

In [ ]:
accounts['country'].unique()

array(['US', 'IN', 'UK', 'CA', 'DE', 'AU', 'FR'], dtype=object)

In [ ]:
accounts['referral_source'].unique()

array(['partner', 'other', 'organic', 'event', 'ads'], dtype=object)

In [ ]:
accounts['plan_tier'].unique()

array(['Basic', 'Enterprise', 'Pro'], dtype=object)

In [ ]:
final_df = accounts.copy()

In [ ]:
feature_usage.sample(2)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
13248,U-539107,S-43c2e3,2024-11-12,feature_38,7,3115,1,False
71,U-b07117,S-e7b281,2023-01-16,feature_3,19,11210,0,False


In [ ]:
subscription.sample(2)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
895,S-a96f6c,A-b30291,2024-10-23,NaN,Pro,13,0,0,True,False,False,False,monthly,True
1074,S-7d2c1b,A-34d880,2024-06-04,NaN,Pro,9,0,0,True,False,False,False,monthly,True


In [ ]:
subscription['subscription_id'].nunique()

5000

In [ ]:
feature_usage['subscription_id'].nunique()

4967

In [ ]:
feature_usage['usage_date'] = pd.to_datetime(feature_usage['usage_date'])

In [ ]:
feature_usage_cpy = pd.get_dummies(feature_usage, columns=['feature_name'], dtype=int)
feature_usage_cpy.drop(columns=['usage_id'], inplace=True)
feature_usage_cpy.sample(2)

,subscription_id,usage_date,usage_count,usage_duration_secs,error_count,is_beta_feature,feature_name_feature_1,feature_name_feature_10,feature_name_feature_11,feature_name_feature_12,...,feature_name_feature_37,feature_name_feature_38,feature_name_feature_39,feature_name_feature_4,feature_name_feature_40,feature_name_feature_5,feature_name_feature_6,feature_name_feature_7,feature_name_feature_8,feature_name_feature_9
13963,S-cde950,2023-03-07,12,7008,3,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22801,S-1fddda,2023-10-23,14,7896,0,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
cols_to_sum = feature_usage_cpy.columns.difference(['subscription_id', 'usage_date'])
feature_usage_cpy = feature_usage_cpy.groupby('subscription_id').agg({
    'usage_date': 'max',
    **{col: 'sum' for col in cols_to_sum}
}).reset_index()

In [ ]:
subscription = subscription.merge(feature_usage_cpy, on='subscription_id', how='left')

In [ ]:
subscription['billing_frequency']

,billing_frequency
0,monthly
1,monthly
2,annual
3,monthly
4,monthly
...,...
4995,monthly
4996,monthly
4997,annual
4998,monthly


In [ ]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   subscription_id          5000 non-null   object        
 1   account_id               5000 non-null   object        
 2   start_date               5000 non-null   object        
 3   end_date                 486 non-null    object        
 4   plan_tier                5000 non-null   object        
 5   seats                    5000 non-null   int64         
 6   mrr_amount               5000 non-null   int64         
 7   arr_amount               5000 non-null   int64         
 8   is_trial                 5000 non-null   bool          
 9   upgrade_flag             5000 non-null   bool          
 10  downgrade_flag           5000 non-null   bool          
 11  churn_flag               5000 non-null   bool          
 12  billing_frequency        5000 non-

In [ ]:
subscription['start_date'] = pd.to_datetime(subscription['start_date'])
subscription['end_date'] = pd.to_datetime(subscription['end_date'])

In [ ]:
subscription_cpy = pd.get_dummies(subscription, columns=['plan_tier', 'billing_frequency'], dtype=int)
subscription_cpy.drop(columns=['churn_flag'], inplace=True)
subscription_cpy.drop(columns=['subscription_id'], inplace=True)
subscription_cpy.sample(2)

,account_id,start_date,end_date,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,auto_renew_flag,...,feature_name_feature_8,feature_name_feature_9,is_beta_feature,usage_count,usage_duration_secs,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,billing_frequency_annual,billing_frequency_monthly
3974,A-396e5f,2024-10-05,NaT,6,1194,14328,False,False,False,True,...,0.0,0.0,1.0,64.0,28393.0,0,1,0,0,1
4971,A-d792a6,2023-03-18,NaT,9,0,0,True,False,False,False,...,0.0,0.0,0.0,52.0,18797.0,0,0,1,0,1


In [ ]:
subscription_cpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 60 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   account_id                 5000 non-null   object        
 1   start_date                 5000 non-null   datetime64[ns]
 2   end_date                   486 non-null    datetime64[ns]
 3   seats                      5000 non-null   int64         
 4   mrr_amount                 5000 non-null   int64         
 5   arr_amount                 5000 non-null   int64         
 6   is_trial                   5000 non-null   bool          
 7   upgrade_flag               5000 non-null   bool          
 8   downgrade_flag             5000 non-null   bool          
 9   auto_renew_flag            5000 non-null   bool          
 10  usage_date                 4967 non-null   datetime64[ns]
 11  error_count                4967 non-null   float64       
 12  featur

In [ ]:
col_to_sum = subscription_cpy.columns.difference(['account_id', 'start_date', 'end_date', 'usage_date'])
subscription_cpy = subscription_cpy.groupby('account_id').agg({
    'start_date': 'min',
    'end_date': 'max',
    'usage_date': 'max',
    **{col: 'sum' for col in col_to_sum}
}).reset_index()

In [ ]:
final_df = final_df.merge(subscription_cpy, on='account_id', how='left')

In [ ]:
final_df


,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats_x,is_trial_x,churn_flag,...,is_beta_feature,is_trial_y,mrr_amount,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,seats_y,upgrade_flag,usage_count,usage_duration_secs
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,4.0,2,12603,3,2,5,312,1,535.0,152339.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,...,2.0,0,10004,4,1,3,176,3,355.0,101136.0
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,...,5.0,1,18286,4,4,7,282,1,821.0,251210.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,...,5.0,1,9275,3,1,3,209,2,382.0,102528.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,...,4.0,1,48761,0,4,5,424,2,579.0,215779.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False,...,5.0,1,4447,4,1,3,221,0,402.0,130242.0
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False,...,6.0,3,12137,2,3,5,188,3,476.0,145972.0
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True,...,3.0,4,16613,2,4,3,202,0,458.0,121379.0
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False,...,4.0,2,19382,4,4,4,341,1,571.0,180056.0


In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 69 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   account_id                 500 non-null    object        
 1   account_name               500 non-null    object        
 2   industry                   500 non-null    object        
 3   country                    500 non-null    object        
 4   signup_date                500 non-null    object        
 5   referral_source            500 non-null    object        
 6   plan_tier                  500 non-null    object        
 7   seats_x                    500 non-null    int64         
 8   is_trial_x                 500 non-null    bool          
 9   churn_flag                 500 non-null    bool          
 10  start_date                 500 non-null    datetime64[ns]
 11  end_date                   312 non-null    datetime64[ns]
 12  usage_da

In [ ]:
support.sample(2)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
336,T-130a82,A-cb5333,2023-08-22,2023-08-23 01:00:00,25.0,low,35,3.0,False
301,T-502019,A-4e631b,2024-09-23,2024-09-23 20:00:00,20.0,low,18,4.0,False


In [ ]:
support['account_id'].nunique()

492

In [ ]:
support['submitted_at'] = pd.to_datetime(support['submitted_at'])
support['closed_at'] = pd.to_datetime(support['closed_at'])

In [ ]:
support_cpy = pd.get_dummies(support, columns=['priority'], dtype=int)
support_cpy.drop(columns=['ticket_id'], inplace=True)
support_cpy.sample(2)

,account_id,submitted_at,closed_at,resolution_time_hours,first_response_time_minutes,satisfaction_score,escalation_flag,priority_high,priority_low,priority_medium,priority_urgent
476,A-832ec2,2024-02-28,2024-02-28 20:00:00,20.0,68,NaN,False,0,0,1,0
631,A-bb3bd4,2023-12-05,2023-12-07 09:00:00,57.0,21,NaN,False,0,0,1,0


In [ ]:
support_cpy = support_cpy.groupby('account_id').agg({
    'submitted_at': ['min', 'max'],
    'closed_at': ['min', 'max'],
    'resolution_time_hours': 'mean',
    'first_response_time_minutes': 'mean',
    'satisfaction_score': 'mean',
    'escalation_flag': 'sum',
    'priority_urgent': 'sum',
    'priority_high': 'sum',
    'priority_low': 'sum',
    'priority_medium': 'sum'})

In [ ]:
support_cpy.columns = [
    '_'.join(col).strip() if isinstance(col, tuple) else col
    for col in support_cpy.columns
]

In [ ]:
final_df = final_df.merge(support_cpy, on='account_id', how='left')

In [ ]:
final_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats_x', 'is_trial_x', 'churn_flag',
       'start_date', 'end_date', 'usage_date', 'arr_amount', 'auto_renew_flag',
       'billing_frequency_annual', 'billing_frequency_monthly',
       'downgrade_flag', 'error_count', 'feature_name_feature_1',
       'feature_name_feature_10', 'feature_name_feature_11',
       'feature_name_feature_12', 'feature_name_feature_13',
       'feature_name_feature_14', 'feature_name_feature_15',
       'feature_name_feature_16', 'feature_name_feature_17',
       'feature_name_feature_18', 'feature_name_feature_19',
       'feature_name_feature_2', 'feature_name_feature_20',
       'feature_name_feature_21', 'feature_name_feature_22',
       'feature_name_feature_23', 'feature_name_feature_24',
       'feature_name_feature_25', 'feature_name_feature_26',
       'feature_name_feature_27', 'feature_name_feature_28',
       'feature_name_feature

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 81 columns):
 #   Column                            Non-Null Count  Dtype         
---  ------                            --------------  -----         
 0   account_id                        500 non-null    object        
 1   account_name                      500 non-null    object        
 2   industry                          500 non-null    object        
 3   country                           500 non-null    object        
 4   signup_date                       500 non-null    object        
 5   referral_source                   500 non-null    object        
 6   plan_tier                         500 non-null    object        
 7   seats_x                           500 non-null    int64         
 8   is_trial_x                        500 non-null    bool          
 9   churn_flag                        500 non-null    bool          
 10  start_date                        500 non-null    

In [ ]:
final_df.sample(2)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats_x,is_trial_x,churn_flag,...,closed_at_min,closed_at_max,resolution_time_hours_mean,first_response_time_minutes_mean,satisfaction_score_mean,escalation_flag_sum,priority_urgent_sum,priority_high_sum,priority_low_sum,priority_medium_sum
51,A-94f8c9,Company_51,HealthTech,US,2024-03-29,other,Basic,13,False,False,...,2023-11-14 21:00:00,2024-09-01 03:00:00,47.333333,87.666667,5.0,0.0,2.0,0.0,1.0,0.0
70,A-2922b6,Company_70,HealthTech,US,2024-11-14,organic,Basic,15,False,False,...,2024-10-03 03:00:00,2024-11-13 04:00:00,15.500000,103.000000,4.0,0.0,1.0,1.0,0.0,0.0


In [ ]:
(final_df['seats_x'] == final_df['seats_y']).all()

np.False_

In [ ]:
(final_df['is_trial_x'] == final_df['is_trial_y']).all()

np.False_

In [ ]:
final_df.rename(columns={

    'is_trial_x': 'is_trial_current',
    'is_trial_y': 'trial_count'
}, inplace=True)

In [ ]:
final_df.drop(columns=['seats_y'], inplace=True)

In [ ]:
final_df['signup_date'] = pd.to_datetime(final_df['signup_date'])

In [ ]:
def drop_columns(df, features):
    df.drop(columns=features, inplace=True)

In [ ]:
class FeatureConstructor(BaseEstimator, TransformerMixin):

    def __init__(self, day_features=None, diff_features=None, ratio_features=None):
        self.day_features = day_features
        self.diff_features = diff_features
        self.ratio_features = ratio_features

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = X.copy()
        if self.day_features:
            for new_col, col1, col2 in self.day_features:
                df[new_col] = (df[col1] - df[col2]).dt.days

        if self.diff_features:
            for new_col, col1, col2 in self.diff_features:
                df[new_col] = df[col1] - df[col2]

        if self.ratio_features:
            for new_col, col1, col2 in self.ratio_features:
                df[new_col] = df[col1] / df[col2]

        df['subscription_duration_days'] = (df['end_date'] - df['start_date']).dt.days
        df.loc[df['start_date'].isna() & df['end_date'].isna(), 'subscription_duration_days'] = 0
        today = df['usage_date'].max()
        df.loc[df['end_date'].isna() & df['start_date'].notna(), 'subscription_duration_days'] = (today - df['start_date']).dt.days

        df['ticket_span_days'] = (df['closed_at_max'] - df['submitted_at_min']).dt.days
        df.loc[df['submitted_at_min'].isna() & df['closed_at_max'].isna(), 'ticket_span_days'] = 0
        df.loc[df['closed_at_max'].isna() & df['submitted_at_min'].notna(), 'ticket_span_days'] = (today - df['submitted_at_min']).dt.days

        df["expected_usage"] = df["seats_x"] * 10
        df["usage_gap"] = df["usage_count"] - df["expected_usage"]

        df['support_flag'] = (df['resolution_time_hours_mean'] > 0).astype(int)
        df["usage_per_day"] = df["usage_count"] / (df["account_age_days"] + 1)

        df['support_pressure'] = (
            df['priority_urgent_sum'] * 4 +
            df['priority_high_sum'] * 3 +
            df['priority_medium_sum'] * 2 +
            df['priority_low_sum']
        )

        df["support_per_usage"] = df["support_pressure"] / (df["usage_count"] + 1)
        df['support_risk'] = 5 - df['satisfaction_score_mean']

        feature_cols = [c for c in df.columns if "feature_name_" in c]
        df['feature_adoption_score'] = df[feature_cols].sum(axis=1)
        df['features_used_count'] = (df[feature_cols] > 0).sum(axis=1)
        df["stickiness"] = df["features_used_count"] / (df["account_age_days"] + 1)

        df["account_age_ratio"] = df["account_age_days"] / (df["subscription_duration_days"] + 1)
        df["usage_per_seat"] = df["usage_count"] / (df["seats_x"] + 1)

        observation_date = df['usage_date'].max()
        df['days_since_last_usage'] = (observation_date - df['usage_date']).dt.days

        df["frustration_score"] = (df["support_pressure"] * 0.5 + (5 - df["satisfaction_score_mean"].fillna(3)) * 2)
        df["revenue_per_seat"] = df["arr_amount"] / (df["seats_x"] + 1)

        return df

In [ ]:
def select_features(df):

    feature_cols = [col for col in df.columns if "feature_name_" in col]
    IDs = ['account_id', 'account_name']
    raw_dates = [
        'signup_date',
        'start_date',
        'end_date',
        'usage_date',
        'submitted_at_min',
        'submitted_at_max',
        'closed_at_min',
        'closed_at_max'
    ]
    features_to_remove = IDs + raw_dates + feature_cols
    return df.drop(columns=[c for c in features_to_remove if c in df.columns])

In [ ]:
def drop_columns(df):
    return df.drop(columns=['industry','country','referral_source','plan_tier'], errors="ignore")

drop_columns_transformer = FunctionTransformer(drop_columns)

In [ ]:
def fill_subscription_duration(df):
    df = df.copy()
    df["subscription_duration_days"] = df["subscription_duration_days"].fillna(df["account_age_days"])
    return df

fill_duration_transformer = FunctionTransformer(fill_subscription_duration)

In [ ]:
X = final_df.drop(columns=['churn_flag'])
y = final_df['churn_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
set_config(transform_output="pandas")

imputation = ColumnTransformer(
    transformers=[
        ('constant_imputation', SimpleImputer(strategy='constant', fill_value=0), [
            'resolution_time_hours_mean',
            'first_response_time_minutes_mean',
            'escalation_flag_sum',
            'priority_urgent_sum',
            'priority_high_sum',
            'priority_low_sum',
            'priority_medium_sum',
            'upgrade_flag',
            'downgrade_flag',
        ]),
        ('median_imputation', SimpleImputer(strategy='median'), ['satisfaction_score_mean'])
    ],
    remainder='passthrough',
    verbose_feature_names_out=False
)

feature_construction = FeatureConstructor(
    day_features=[
        ('account_age_days', 'usage_date', 'signup_date')
    ],
    diff_features=[
        ('plan_momentum', 'upgrade_flag', 'downgrade_flag')
    ],
    ratio_features=[
        ('avg_usage_time', 'usage_duration_secs', 'usage_count'),
        ('revenue_per_seat_ratio', 'arr_amount', 'seats_x')
    ]
)

select_features_transformer = FunctionTransformer(select_features, validate=False)

feature_transformation = ColumnTransformer(
    transformers=[
        ('onehotencoding', OneHotEncoder(sparse_output=False, drop='first'), ['industry', 'country', 'referral_source']),
        ('ordinalencoding', OrdinalEncoder(), ['plan_tier'])
    ],
    remainder='passthrough',
    verbose_feature_names_out=False
)

feature_drop = FunctionTransformer(drop_columns, validate=False)

model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    class_weight='balanced',
    random_state=42
)

In [ ]:
pipe = Pipeline([
    ('imputation', imputation),
    ('feature_construction', feature_construction),
    ('feature_selection', select_features_transformer),
    ('feature_transformation', feature_transformation),
    ('feature_drop', feature_drop),
    ('model', model)
    ])

In [ ]:
pipe.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 93, number of negative: 307
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000484 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2934
[LightGBM] [Info] Number of data points in the train set: 400, number of used features: 57
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best g

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('imputation',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('constant_imputation',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant'),
                                                  ['resolution_time_hours_mean',
                                                   'first_response_time_minutes_mean',
                                                   'escalation_flag_sum',
                                                   'priority_urgent_sum',
                                                   'priority_high_sum',
                                                   'priority_low_sum',
                                                   'priority_medium_sum',
                                                   'upgrade_flag',
                                                   'downgra...
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['industry', 'country',
                                                   'referral_source']),
                                                 ('ordinalencoding',
                                                  OrdinalEncoder(),
                                                  ['plan_tier'])],
                                   verbose_feature_names_out=False)),
                ('feature_drop',
                 FunctionTransformer(func=<function drop_columns at 0x7dcb39634ae0>)),
                ('model',
                 LGBMClassifier(class_weight='balanced', learning_rate=0.05,
                                n_estimators=300, random_state=42))])

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
import numpy as np
print(np.unique(y_test, return_counts=True))

(array([False,  True]), array([83, 17]))


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[76  7]
 [15  2]]


In [ ]:
y_proba = pipe.predict_proba(X_test)[:, 1]

In [ ]:
for t in [1,0.9,0.8,0.7,0.6,0.5,0.55, 0.4, 0.3, 0.25, 0.2, 0.1, 0.05]:
    y_pred = (y_proba > t).astype(int)
    print(f"Threshold: {t}")
    print(confusion_matrix(y_test, y_pred))

Threshold: 1
[[83  0]
 [17  0]]
Threshold: 0.9
[[83  0]
 [16  1]]
Threshold: 0.8
[[82  1]
 [16  1]]
Threshold: 0.7
[[80  3]
 [15  2]]
Threshold: 0.6
[[78  5]
 [15  2]]
Threshold: 0.5
[[76  7]
 [15  2]]
Threshold: 0.55
[[77  6]
 [15  2]]
Threshold: 0.4
[[73 10]
 [14  3]]
Threshold: 0.3
[[69 14]
 [13  4]]
Threshold: 0.25
[[63 20]
 [12  5]]
Threshold: 0.2
[[61 22]
 [11  6]]
Threshold: 0.1
[[54 29]
 [11  6]]
Threshold: 0.05
[[40 43]
 [ 7 10]]


AttributeError: 'Pipeline' object has no attribute 'info'